import Addresses from './Addresses'
import Description from './Description'
import Gallery from './Gallery'
import Hero from './Hero'
import Layout from './Layout'
import Services from './Services'
import SocialNetworks from './SocialNetworks'
import Video from './Video'
import WorkingHours from './WorkingHours'

export { Addresses }
export { Description }
export { Gallery }
export { Hero }
export { Layout }
export { Services }
export { SocialNetworks }
export { Video }
export { WorkingHours }
