import CameraIcon from './CameraIcon'
import CategoryIcon from './CategoryIcon'
import ClockIcon from './ClockIcon'
import CloseIcon from './CloseIcon'
import CommentIcon from './CommentIcon'
import DateIcon from './DateIcon'
import EmailIcon from './EmailIcon'
import GalleryIcon from './GalleryIcon'
import GridIcon from './GridIcon'
import HamburgerIcon from './HamburgerIcon'
import LocationIcon from './LocationIcon'
import MultilineIcon from './MultilineIcon'
import PhonIcon from './PhonIcon'
import SearchIcon from './SearchIcon'
import ShareIcon from './ShareIcon'
import StarIcon from './StarIcon'
import ViewPostIcon from './ViewPostIcon'

export { CameraIcon }
export { CategoryIcon }
export { ClockIcon }
export { CloseIcon }
export { CommentIcon }
export { DateIcon }
export { EmailIcon }
export { GalleryIcon }
export { GridIcon }
export { HamburgerIcon }
export { LocationIcon }
export { MultilineIcon }
export { PhonIcon }
export { SearchIcon }
export { ShareIcon }
export { StarIcon }
export { ViewPostIcon }
